# -*- coding: utf-8 -*-
"""_init_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnQrGZammISGuBZeJIWha0OCKlC0J2ql
"""

from data_loader import load_data, train_valid_split, one_hot_encode

# You can now call these functions, e.g.:
# data = load_data()
# train_data, valid_data = train_valid_split(data)
# encoded_data = one_hot_encode(data)