# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2n-CyN3p7U3rRPa_1OUCZXXLAqgk4Xi
"""

"""
Inference Script
Evaluate trained models on test sets
"""

import argparse
import numpy as np
import pickle
from sklearn.metrics import f1_score, precision_score, recall_score

from utils.data_loader import load_data
from ann.objective_functions import cross_entropy


def parse_arguments():
    """
    Parse command-line arguments for inference.
    """
    parser = argparse.ArgumentParser(description='Run inference on test set')

    parser.add_argument('--model_path', type=str, required=True,
                        help='Path to saved model weights (e.g., model.pkl)')

    parser.add_argument('--dataset', type=str, choices=['mnist', 'fashion_mnist'], default='mnist',
                        help='Dataset to evaluate on')

    parser.add_argument('--batch_size', type=int, default=32,
                        help='Batch size for inference')

    parser.add_argument('--hidden_layers', type=int, nargs='+', default=[128],
                        help='List of hidden layer sizes')

    parser.add_argument('--num_neurons', type=int, default=128,
                        help='Number of neurons in hidden layers')

    parser.add_argument('--activation', type=str,
                        choices=['relu', 'sigmoid', 'tanh'], default='relu',
                        help='Activation function')

    return parser.parse_args()


def load_model(model_path):
    """
    Load trained model from disk.
    """
    with open(model_path, 'rb') as f:
        model = pickle.load(f)
    return model


def evaluate_model(model, X_test, y_test):
    """
    Evaluate model on test data.

    Returns:
        Dictionary - logits, loss, accuracy, f1, precision, recall
    """
    logits = model.forward(X_test)

    # Compute loss
    loss = cross_entropy(logits, y_test)

    y_true = np.argmax(y_test, axis=1)
    y_pred = np.argmax(logits, axis=1)

    accuracy = np.mean(y_true == y_pred)
    f1 = f1_score(y_true, y_pred, average='macro')
    precision = precision_score(y_true, y_pred, average='macro', zero_division=0)
    recall = recall_score(y_true, y_pred, average='macro', zero_division=0)

    return {
        "logits": logits,
        "loss": loss,
        "accuracy": accuracy,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }


def main():
    """
    Main inference function.
    """
    args = parse_arguments()

    print("Loading test data...")
    # load_data returns 6 values: X_train, y_train, X_val, y_val, X_test, y_test
    _, _, _, _, X_test, y_test = load_data()

    print("Loading trained model...")
    model = load_model(args.model_path)

    print("Running inference...")
    results = evaluate_model(model, X_test, y_test)

    print("\nEvaluation complete!")
    print(f"Loss: {results['loss']:.4f}")
    print(f"Accuracy: {results['accuracy']:.4f}")
    print(f"F1 Score: {results['f1']:.4f}")
    print(f"Precision: {results['precision']:.4f}")
    print(f"Recall: {results['recall']:.4f}")

    return results


if __name__ == '__main__':
    main()