# -*- coding: utf-8 -*-
"""sweep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtyzbNCAxiV1Q6ab8NwLAvrBzmcJxDhc
"""

import wandb
from src.train import model
from src.utils.data_loader import load_data

# Load data once globally
X_train, y_train, X_valid, y_valid, X_test, y_test = load_data("mnist")

sweep_config = {
    "method": "bayes",
    "metric": {"name": "val_accuracy", "goal": "maximize"},
    "parameters": {
        "epochs": {"values": [5, 10]},
        "number_hidden_layer": {"values": [3, 4, 5]},
        "number_neurons": {"values": [32, 64, 128]},
        "learning_rate": {"values": [1e-3, 1e-4]},
        "optimizer": {"values": [
            "stochastic_gradient_descent",
            "momentum_gradient_descent",
            "nesterov_gradient_descent",
            "rmsprop_gradient_descent",
            "adam_gradient_descent",
            "nadam_gradient_descent"
        ]},
        "batch_size": {"values": [16, 32, 64]},
        "weight_ini_method": {"values": ["random", "Xavier"]},
        "active_function_hidden": {"values": ["sigmoid", "tanh"]},
        "active_function_output": {"values": ["softmax"]},
        "epsilon": {"values": [1e-8]},
        "beta": {"values": [0.9]},
        "beta1": {"values": [0.9]},
        "beta2": {"values": [0.99]},
        "weight_decay": {"values": [0, 0.0005, 0.5]}
    }
}

sweep_id = wandb.sweep(sweep=sweep_config, project="ASSIGNMENT_1")


def main():
    with wandb.init() as run:
        run_name = (
            "hiden_ac-" + wandb.config.active_function_hidden +
            "_hs-" + str(wandb.config.number_hidden_layer) +
            "_epc-" + str(wandb.config.epochs) +
            "_hl-" + str(wandb.config.number_neurons) +
            "_wd-" + str(wandb.config.weight_decay) +
            "_learning_rate-" + str(wandb.config.learning_rate) +
            "_opt-" + str(wandb.config.optimizer) +
            "_bs-" + str(wandb.config.batch_size) +
            "_wi-" + str(wandb.config.weight_ini_method)
        )
        wandb.run.name = run_name

        model(
            wandb.config.learning_rate,
            X_train,
            y_train,
            wandb.config.epochs,
            wandb.config.optimizer,
            wandb.config.active_function_hidden,
            wandb.config.active_function_output,
            wandb.config.number_hidden_layer,
            wandb.config.number_neurons,
            wandb.config.weight_ini_method,
            wandb.config.epsilon,
            wandb.config.weight_decay,
            wandb.config.batch_size,
            wandb.config.beta,
            wandb.config.beta1,
            wandb.config.beta2
        )


wandb.agent(sweep_id, function=main, count=4)
wandb.finish()

